import "@/app/globals.css";
import { Inter } from "next/font/google";
import { LanguageProvider } from "@/components/LanguageProvider";
import { Fragment } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (_) {}
              })();
            `,
          }}
        />
      </head>
      <LanguageProvider>
        <body className={inter.className}>
          <Fragment>
            <main>{children}</main>
          </Fragment>
        </body>
      </LanguageProvider>
    </html>
  );
}
