import "@/app/globals.css";
import { Inter } from "next/font/google";
import { LanguageProvider } from "@/components/LanguageProvider";
import { Fragment } from "react";
import Navbar from "@/components/UI/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <LanguageProvider>
        <body className={inter.className}>
          <Fragment>
            <Navbar />
            <main>{children}</main>
          </Fragment>
        </body>
      </LanguageProvider>
    </html>
  );
}
